
package com.bt.service;

import java.net.MalformedURLException;
import java.net.URL;
import javax.jws.HandlerChain;
import javax.xml.namespace.QName;
import javax.xml.ws.Service;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceException;
import javax.xml.ws.WebServiceFeature;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebServiceClient(name = "TariffServiceImplService", targetNamespace = "http://service.bt.com/", wsdlLocation = "http://localhost:9999/tariffs?wsdl")
@HandlerChain(file = "TariffServiceImplService_handler.xml")
public class TariffServiceImplService
    extends Service
{

    private final static URL TARIFFSERVICEIMPLSERVICE_WSDL_LOCATION;
    private final static WebServiceException TARIFFSERVICEIMPLSERVICE_EXCEPTION;
    private final static QName TARIFFSERVICEIMPLSERVICE_QNAME = new QName("http://service.bt.com/", "TariffServiceImplService");

    static {
        URL url = null;
        WebServiceException e = null;
        try {
            url = new URL("http://localhost:9999/tariffs?wsdl");
        } catch (MalformedURLException ex) {
            e = new WebServiceException(ex);
        }
        TARIFFSERVICEIMPLSERVICE_WSDL_LOCATION = url;
        TARIFFSERVICEIMPLSERVICE_EXCEPTION = e;
    }

    public TariffServiceImplService() {
        super(__getWsdlLocation(), TARIFFSERVICEIMPLSERVICE_QNAME);
    }

    public TariffServiceImplService(WebServiceFeature... features) {
        super(__getWsdlLocation(), TARIFFSERVICEIMPLSERVICE_QNAME, features);
    }

    public TariffServiceImplService(URL wsdlLocation) {
        super(wsdlLocation, TARIFFSERVICEIMPLSERVICE_QNAME);
    }

    public TariffServiceImplService(URL wsdlLocation, WebServiceFeature... features) {
        super(wsdlLocation, TARIFFSERVICEIMPLSERVICE_QNAME, features);
    }

    public TariffServiceImplService(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public TariffServiceImplService(URL wsdlLocation, QName serviceName, WebServiceFeature... features) {
        super(wsdlLocation, serviceName, features);
    }

    /**
     * 
     * @return
     *     returns TariffService
     */
    @WebEndpoint(name = "TariffServiceImplPort")
    public TariffService getTariffServiceImplPort() {
        return super.getPort(new QName("http://service.bt.com/", "TariffServiceImplPort"), TariffService.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns TariffService
     */
    @WebEndpoint(name = "TariffServiceImplPort")
    public TariffService getTariffServiceImplPort(WebServiceFeature... features) {
        return super.getPort(new QName("http://service.bt.com/", "TariffServiceImplPort"), TariffService.class, features);
    }

    private static URL __getWsdlLocation() {
        if (TARIFFSERVICEIMPLSERVICE_EXCEPTION!= null) {
            throw TARIFFSERVICEIMPLSERVICE_EXCEPTION;
        }
        return TARIFFSERVICEIMPLSERVICE_WSDL_LOCATION;
    }

}
