
package com.bt.ws.orderimport;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebService(name = "OrderService", targetNamespace = "http://order.ws.bt.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface OrderService {


    /**
     * 
     * @param arg1
     * @param arg0
     */
    @WebMethod
    @RequestWrapper(localName = "addOrder", targetNamespace = "http://order.ws.bt.com/", className = "com.bt.ws.orderimport.AddOrder")
    @ResponseWrapper(localName = "addOrderResponse", targetNamespace = "http://order.ws.bt.com/", className = "com.bt.ws.orderimport.AddOrderResponse")
    @Action(input = "http://order.ws.bt.com/OrderService/addOrderRequest", output = "http://order.ws.bt.com/OrderService/addOrderResponse")
    public void addOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        Order arg0,
        @WebParam(name = "arg1", targetNamespace = "")
        String arg1);

    /**
     * 
     * @param arg0
     * @return
     *     returns com.bt.ws.orderimport.Order
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getOrder", targetNamespace = "http://order.ws.bt.com/", className = "com.bt.ws.orderimport.GetOrder")
    @ResponseWrapper(localName = "getOrderResponse", targetNamespace = "http://order.ws.bt.com/", className = "com.bt.ws.orderimport.GetOrderResponse")
    @Action(input = "http://order.ws.bt.com/OrderService/getOrderRequest", output = "http://order.ws.bt.com/OrderService/getOrderResponse")
    public Order getOrder(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
