
package com.bt.jaxws.billing;

import javax.xml.ws.WebFault;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.4-b01
 * Generated source version: 2.2
 * 
 */
@WebFault(name = "InvalidCustomerException", targetNamespace = "http://billing.jaxws.bt.com/")
public class InvalidCustomerException_Exception
    extends Exception
{

    /**
     * Java type that goes as soapenv:Fault detail element.
     * 
     */
    private InvalidCustomerException faultInfo;

    /**
     * 
     * @param message
     * @param faultInfo
     */
    public InvalidCustomerException_Exception(String message, InvalidCustomerException faultInfo) {
        super(message);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @param message
     * @param faultInfo
     * @param cause
     */
    public InvalidCustomerException_Exception(String message, InvalidCustomerException faultInfo, Throwable cause) {
        super(message, cause);
        this.faultInfo = faultInfo;
    }

    /**
     * 
     * @return
     *     returns fault bean: com.bt.jaxws.billing.InvalidCustomerException
     */
    public InvalidCustomerException getFaultInfo() {
        return faultInfo;
    }

}
